name: "Docschina Github Action"
description: "印记中文部署"
author: lcxfs1991
branding:
  icon: cloud
  color: red
inputs:
  secretId:
    description: "腾讯云 secretId"
    required: true
  secretKey:
    description: "腾讯云 secretKey"
    required: true
  envId:
    description: "云开发环境 Id"
    required: false
  staticSrcPath:
    description: "静态资源:本地路径"
    required: true
    default: build
  staticDestPath:
    description: "静态资源:云端路径"
    required: false
    default: ""
  bucket:
    description: "COS Bucket"
    required: false
    default: ""
  region:
    description: "COS Region"
    required: false
    default: ""
  skipFiles:
    description: "跳过不上传的文件或目录"
    required: false
    default: ""
outputs:
  deployResult:
    description: "部署结果"
runs:
  using: "node12"
  main: "./index.js"
